/**
 * Salesken Organization APIs
 * <b>Introduction</b><br><br>This is collection of Organization APIs. These are used to create organization, fetch organization records, update organization and invoke organization.<br><br> <b>Authentication</b><br><br> Salesken Organization APIs are authenticated using Basic Authentication with your Authentication API Key and OAuth2. The OAuth2 are available after you sign-up with the Salesken.<br><br> <b>Error Codes</b><br><br> Error codes are defined in superadmin project <a href=\"\">Error Codes</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: itadmin@salesken.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.api;

import io.swagger.model.Body;
import io.swagger.model.Body1;
import io.swagger.model.CreateTeam;
import io.swagger.model.DeleteTeam;
import io.swagger.model.TeamById;
import io.swagger.model.TeamList;
import io.swagger.model.UpdateTeamDetails;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Salesken Organization APIs
 *
 * <p><b>Introduction</b><br><br>This is collection of Organization APIs. These are used to create organization, fetch organization records, update organization and invoke organization.<br><br> <b>Authentication</b><br><br> Salesken Organization APIs are authenticated using Basic Authentication with your Authentication API Key and OAuth2. The OAuth2 are available after you sign-up with the Salesken.<br><br> <b>Error Codes</b><br><br> Error codes are defined in superadmin project <a href=\"\">Error Codes</a>
 *
 * API tests for TeamApi 
 */
public class TeamApiTest {


    private TeamApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://virtserver.swaggerhub.com/Salesken8/Organization-DataTable-Test/1.0.0", TeamApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    /**
     * Create Team
     *
     * Use this API to create a new team. Can be called from the Sales Manager Web App.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTeamTest() {
        Body body = null;
        //CreateTeam response = api.createTeam(body);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Delete Team
     *
     * Use this API to delete the team. Can be called from the Sales Manager Web App.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTeamTest() {
        Integer id = null;
        //DeleteTeam response = api.deleteTeam(id);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * List all Teams of organization
     *
     * Use this API to get all teams / search teams in an organization. Can be called from the Sales Manager Web App.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTeamTest() {
        Integer orgId = null;
        String search = null;
        //TeamList response = api.listTeam(orgId, search);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Get Team by Id
     *
     * Use this API to get a team by Id. Can be called from the Sales Manager Web App.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void teamByIdTest() {
        Integer id = null;
        //TeamById response = api.teamById(id);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    /**
     * Edit / Update Team Details
     *
     * Use this API to edit / update team details such as addition / deletion of team members, edit team name and description and assign / re-assign team owner. Can be called from the Sales Manager Web App.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTeamDetailsTest() {
        Body1 body = null;
        Integer id = null;
        //UpdateTeamDetails response = api.updateTeamDetails(body, id);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
}
